### ISSUE TITLE
Calendar?

### ISSUE THREAD

**Issue by schergr** [dcmeglio/homeassistant-waste_management#11]
I've installed the integration, and have two sensors ( one for each trash service) but I'm not seeing a calendar entity. Is there a way to integrate this into the calendar?

**Comment by dcmeglio** [comment]
The integration just provides the sensors, there is no calendar entity integration.

**Comment by pyrometheous** [comment]
I've been trying to write an automation that triggers 14hrs before a pickup (so I can put out the trash the night before). I was wondering if anyone has used an automation to use the sensor entities to create a calendar entry when the sensors change values.
